### ISSUE TITLE
Смена темы

### ISSUE THREAD

**Issue by WingedLeo** [Kostya12rus/steam_inventory_logger#1]
Кнопка для смены темы (тёмная/светлая)

**Comment by Kostya12rus** [comment]
Реализовал в обновлении https://github.com/Kostya12rus/steam_inventory_logger/commit/2b8a5883b736f7a907ab1279f97d8b835dbea274
Если на этом все, я закрою или ты закрой https://github.com/Kostya12rus/steam_inventory_logger/issues/1

**Comment by Kostya12rus** [comment]
![image](https://github.com/user-attachments/assets/3a6e2af5-7a3e-4f91-b93d-2f3eaf5d57c7)
