### ISSUE TITLE
Без комиссии

### ISSUE THREAD

**Issue by Arwo337** [Kostya12rus/steam_inventory_logger#2]
нужна ещё одна графа в инвентаре и в крафтах которая будет учитывать цену без комиссии при продаже того или иного предмета.

**Comment by Kostya12rus** [comment]
Реализовал в обновлении https://github.com/Kostya12rus/steam_inventory_logger/commit/2b8a5883b736f7a907ab1279f97d8b835dbea274
Только я сделал при наведении курсора на цену продажи, пример будет в картинке

Если на этом все, я закрою или ты закрой https://github.com/Kostya12rus/steam_inventory_logger/issues/2

![image](https://github.com/user-attachments/assets/86db6de3-faca-4a38-8dff-a06ec439f913)
